APACHE_VERSION="2.2.22"
APACHE_TGZ_FILE="apache-${APACHE_VERSION}.tar.gz"

ANT_VERSION="1.8.4"
ANT_CONTRIB_VERSION="1.0b3"
ANT_TGZ_FILE="ant-${ANT_VERSION}.tar.gz"

PHP_VERSION="5.3.20"
LIBMCRYPT_VERSION="2.5.8"
PHP_TGZ_FILE="php-${PHP_VERSION}.tar.gz"

NEWRELIC_VERSION="3.1.5.136"
NEWRELIC_TGZ_FILE="newrelic-${NEWRELIC_VERSION}.tar.gz"

MANIFEST_FILE="manifest.md5sum"
